### ISSUE TITLE
Open File Error

### ISSUE THREAD

**Issue by joshgrift** [wflosin/Drive-A-Car-AI#1]
Sorry to be picky again, but when I run main.py with pygame installed, I get this error:
```
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
Traceback (most recent call last):
  File "main.py", line 421, in <module>
    start_game()
  File "main.py", line 412, in start_game
    game = Game()
  File "main.py", line 46, in __init__
    self.background_image = pg.image.load(os.path.join('rules','bkgrd_map.png')).convert_alpha()
pygame.error: Couldn't open rules/bkgrd_map.png
```
It doesn't seem to exist in the repo. Is it supposed to be background.png from the root folder?

**Comment by wflosin** [comment]
It turns out I didn't import everything that needed to be imported. Hopefully this should actually work now. I also included the model.h5 file that I made after training for 9 hours. This can be seen in action by running the AI_testing.py file.

**Comment by joshgrift** [comment]
```
$ python3 AI_testing.py
pygame 1.9.6
Hello from the pygame community. https://www.pygame.org/contribute.html
2020-09-10 13:29:19.103213: W tensorflow/stream_executor/platform/default/dso_loader.cc:59] Could not load dynamic library 'libcudart.so.10.1'; dlerror: libcudart.so.10.1: cannot open shared object file: No such file or directory
2020-09-10 13:29:19.103238: I tensorflow/stream_executor/cuda/cudart_stub.cc:29] Ignore above cudart dlerror if you do not have a GPU set up on your machine.
Traceback (most recent call last):
  File "AI_testing.py", line 1, in <module>
    from AI import make_model
  File "/home/josh/git/Drive-A-Car-AI/AI.py", line 13, in <module>
    from rl.agents.dqn import DQNAgent 
  File "/home/josh/.local/lib/python3.8/site-packages/rl/__init__.py", line 111, in <module>
    from rl import readline
ImportError: /home/josh/.local/lib/python3.8/site-packages/rl/readline.cpython-38-x86_64-linux-gnu.so: undefined symbol: UP
```

**Comment by wflosin** [comment]
I just added a requirements.txt file with the packages that were used. Here they are pasted below:

pygame==1.9.5
numpy==1.16.2
tf==1.0.0
gym==0.17.2
keras==2.4.3
rl==3.0
tensorflow==2.3.0

Also, check out this thread. Someone suggested having an updated version of CUDA.
[https://github.com/tensorflow/tensorflow/issues/38578](url)
